services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: weatherapp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate:latest
    depends_on:
      - db
    command: [
      "-path", "/scripts",
      "-database", "postgres://postgres:postgrespass@db:5432/weatherapp?sslmode=disable",
      "up"
    ]
    volumes:
      - ./scripts:/scripts

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - migrate
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgrespass
      DB_NAME: weatherapp

      WEATHERAPI_KEY: ${WEATHERAPI_KEY}
      SUBSCRIPTION_TOKEN_SECRET: ${SUBSCRIPTION_TOKEN_SECRET}
    volumes:
      - ./configs/config.yaml:/app/configs/config.yaml:ro

volumes:
  db_data:
